export interface Place {
  name: string;
  slug: string;
  desc: string;
  category: string;
  highlights: string[];
  bestTime: string;
  duration: string;
  emoji: string;
}

export interface StateData {
  name: string;
  slug: string;
  coverImg: string;
  tagline: string;
  tagColor: string;
  icon: string;
  accentColor: string;
  heroDesc: string;
  places: Place[];
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export function slugifyPlace(name: string): string {
  return slugify(name);
}

export const KARNATAKA: StateData = {
  name: 'Karnataka', slug: 'karnataka', coverImg: '/states/karnataka-cover.jpg',
  tagline: 'Heritage & Nature', tagColor: 'text-amber-400', icon: '🏛️', accentColor: 'amber',
  heroDesc: 'From the royal palaces of Mysuru to the ancient ruins of Hampi, from the coffee hills of Coorg to the tech capital Bengaluru — explore every corner of Karnataka.',
  places: [
    { name: 'Bengaluru', slug: 'bengaluru', desc: 'India\'s Silicon Valley and IT capital with vibrant nightlife, beautiful parks like Lalbagh and Cubbon, world-class restaurants, shopping malls, tech parks, and a perfect blend of modern urban life with traditional South Indian culture. Known as the Garden City for its lush greenery and pleasant weather year-round, Bengaluru offers everything from heritage sites like Bangalore Palace to trendy microbreweries and a thriving startup ecosystem.', category: 'Capital City', highlights: ['Lalbagh Botanical Garden', 'Cubbon Park', 'Bangalore Palace', 'MG Road', 'Vidhana Soudha', 'UB City Mall'], bestTime: 'Sep - Feb', duration: '2-3 Days', emoji: '🏙️' },
    { name: 'Mysore', slug: 'mysore', desc: 'The City of Palaces, famous for the magnificent Mysore Palace illuminated by 97,000 bulbs during Dasara, the sacred Chamundi Hills with its ancient Chamundeshwari Temple, the musical Brindavan Gardens, sandalwood products, Mysore silk sarees, and the grand Dasara festival that attracts millions of visitors every year. The city exudes old-world charm with its heritage buildings, yoga centers, and delectable Mysore Pak.', category: 'Heritage City', highlights: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'KRS Dam', 'St. Philomena\'s Church', 'Mysore Zoo'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏛️' },
    { name: 'Mangalore', slug: 'mangalore', desc: 'Coastal gem of Karnataka with stunning beaches, ancient temples like Kadri Manjunath, delicious seafood cuisine, and the gateway to the Western Ghats. Known for its cashew processing industry and Udupi-style vegetarian food that has gained worldwide fame. The city offers a unique blend of coastal beauty, spiritual heritage, and culinary excellence.', category: 'Coastal City', highlights: ['Panambur Beach', 'Someshwara Temple', 'Kadri Temple', 'Tannirbhavi Beach', 'Sultan Battery', 'Pilikula Nisargadhama'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏖️' },
    { name: 'Hampi', slug: 'hampi', desc: 'UNESCO World Heritage Site with breathtaking ruins of the Vijayanagara Empire spread across 26 square kilometers. The surreal boulder-strewn landscape, ancient temples like Virupaksha, the iconic Stone Chariot, the Queen\'s Bath, and the massive boulder formations create one of India\'s most photographed archaeological sites. A paradise for history lovers, photographers, and backpackers from around the world.', category: 'Heritage', highlights: ['Virupaksha Temple', 'Stone Chariot', 'Hemakuta Hill', 'Tungabhadra River', 'Queen\'s Bath', 'Vittala Temple'], bestTime: 'Oct - Feb', duration: '2-3 Days', emoji: '🏛️' },
    { name: 'Coorg (Kodagu)', slug: 'coorg', desc: 'The Scotland of India — lush coffee plantations stretching across misty hills, cascading waterfalls like Abbey Falls, rich Kodava culture with unique traditions and cuisine, and dense forests teeming with wildlife. Perfect for nature lovers, trekkers, and anyone seeking a peaceful mountain retreat. The aroma of freshly brewed coffee, the sight of mist-covered hills, and the warmth of Kodava hospitality make Coorg unforgettable.', category: 'Hill Station', highlights: ['Abbey Falls', 'Raja\'s Seat', 'Dubare Elephant Camp', 'Coffee Plantations', 'Iruppu Falls', 'Namdroling Monastery'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Chikmagalur', slug: 'chikmagalur', desc: 'Coffee capital of Karnataka nestled in the Western Ghats. Home to Mullayanagiri — the highest peak in Karnataka at 1,930 meters — and famous for its aromatic coffee estates, serene homestays, breathtaking mountain trails, and beautiful waterfalls like Hebbe and Jhari. The town offers a perfect escape from city life with its cool climate, misty mornings, and endless green landscapes.', category: 'Hill Station', highlights: ['Mullayanagiri Peak', 'Baba Budangiri', 'Hebbe Falls', 'Coffee Estates', 'Kudremukh Trek', 'Bhadra Wildlife Sanctuary'], bestTime: 'Sep - Mar', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Hassan', slug: 'hassan', desc: 'Gateway to Karnataka\'s architectural treasures including the stunning Hoysala temples of Belur and Halebidu — masterpieces of intricate stone carving from the 12th century. The colossal monolithic Gomateshwara statue at Shravanabelagola, standing 57 feet tall atop Vindhyagiri Hill, is one of the world\'s tallest free-standing monolithic statues and an important Jain pilgrimage center.', category: 'Heritage', highlights: ['Belur Temple', 'Halebidu Temple', 'Shravanabelagola', 'Gomateshwara Statue', 'Gorur Dam', 'Chennakeshava Temple'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Hubli–Dharwad', slug: 'hubli-dharwad', desc: 'Twin cities forming a major commercial and educational hub of North Karnataka. Known for their prestigious educational institutions, bustling wholesale markets, beautiful temples like the ancient Chandramouleshwara, serene Unkal Lake, and as a strategic gateway to historic sites like the Bijapur monuments and the beaches of Goa.', category: 'Commercial Hub', highlights: ['Chandramouleshwara Temple', 'Unkal Lake', 'Indira Glass House', 'Nrupatunga Hill', 'Siddharoodha Math', 'Bannerughatta'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Belgaum', slug: 'belgaum', desc: 'Border city with a rich cultural heritage straddling Karnataka and Maharashtra. Known for its pleasant weather year-round, the ancient Belgaum Fort with its impressive bastions, beautiful Jain temples like Kamal Basti, the stunning Godchinamalaki Falls, and a unique melting pot of Maharashtrian and Kannada cultures with delicious culinary traditions blending both cuisines.', category: 'Border City', highlights: ['Belgaum Fort', 'Kamal Basti', 'Gokak Falls', 'Godchinamalaki Falls', 'Jamboti Hills', 'Military Mahadeva Temple'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Gulbarga (Kalaburagi)', slug: 'gulbarga', desc: 'Historic city with impressive Islamic architecture from the Bahmani Sultanate era. The massive Gulbarga Fort is one of the largest forts in South India, while the Jama Masjid inside is modeled on the great mosque of Cordoba in Spain. The city is also home to the revered Sharana Basaveshwara Temple and the tomb of Khwaja Bande Nawaz, attracting both history enthusiasts and spiritual seekers.', category: 'Historic City', highlights: ['Gulbarga Fort', 'Jama Masjid', 'Sharana Basaveshwara Temple', 'Khwaja Bande Nawaz', 'Shri Sharanabasaveshwara Temple', 'Chor Gumbad'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Bellary', slug: 'bellary', desc: 'Mining and industrial hub surrounded by historic forts and natural beauty. The Bellary Fort, built by Hanumappa Nayaka on top of the Ballari Gudda hill, offers panoramic views of the city. The city serves as a gateway to Hampi, one of India\'s greatest UNESCO World Heritage Sites, and the scenic Tungabhadra Dam area.', category: 'Industrial City', highlights: ['Bellary Fort', 'Kumaraswamy Temple', 'Hampi Gateway', 'Tungabhadra Dam', 'Daroji Bear Sanctuary', 'Kuntegadda Park'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Hospet', slug: 'hospet', desc: 'The main gateway to Hampi and the Tungabhadra Dam area. This bustling town serves as the primary base for the millions of tourists visiting the UNESCO World Heritage Site of Hampi every year. The Tungabhadra Dam offers beautiful gardens and boat rides, while the nearby Sanapur Lake and Anegundi village provide additional exploration opportunities.', category: 'Gateway to Hampi', highlights: ['Tungabhadra Dam', 'Hampi Access Point', 'Sanapur Lake', 'Anegundi Village', 'Chitradurga Gateway', 'Garden Park'], bestTime: 'Oct - Feb', duration: '2-3 Days', emoji: '🗺️' },
    { name: 'Gadag', slug: 'gadag', desc: 'Rich in architectural heritage with stunning temples from the Chalukya and Hoysala periods. The Trikuteshwara Temple complex with its three Shiva lingas is a masterpiece of Western Chalukya architecture. The town is also the birthplace of the legendary Kannada poet Kumaravyasa, who wrote the Mahabharata in Kannada, and the nearby Lakkundi site has over 100 ancient temples.', category: 'Temple Town', highlights: ['Trikuteshwara Temple', 'Veera Narayana Temple', 'Lakkundi Heritage Site', 'Dambal', 'Sudi Temple Complex', 'Magadi Bird Sanctuary'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🛕' },
    { name: 'Davangere', slug: 'davangere', desc: 'Famous across India for its signature Davangere Benne Dosa — a crispy butter dosa that food lovers travel miles to taste. This city is a major agricultural and educational hub of Central Karnataka, surrounded by scenic Channagiri hills, beautiful lakes like Kunduvada Kere and Sulekere (one of the largest lakes in Karnataka), and a growing industrial sector.', category: 'Culinary City', highlights: ['Benne Dosa', 'Channagiri Hills', 'Kunduvada Kere Lake', 'Sulekere Lake', 'Shivamogga Gateway', 'Durgambika Temple'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🍽️' },
    { name: 'Chitradurga', slug: 'chitradurga', desc: 'Known as the "Stone Fortress City" with the massive Chitradurga Fort spanning seven hills, built over centuries by various dynasties. Legend has it that the brave Onake Obavva single-handedly fought invaders through a crevice in the fort walls. The mysterious Chandravalli Caves, Hidimbeshwara Temple, and Ankali Mutt add to this city\'s legendary status from the Mahabharata period.', category: 'Fort City', highlights: ['Chitradurga Fort', 'Chandravalli Caves', 'Hidimbeshwara Temple', 'Ankali Mutt', 'Obavvana Kindi', 'Jogimatti Hills'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏰' },
    { name: 'Shimoga (Shivamogga)', slug: 'shimoga', desc: 'Called the "Gateway of Malnad" with stunning Jog Falls — India\'s second highest waterfall at 253 meters — created by the Sharavathi River plunging down in four distinct cascades. Surrounded by lush green forests, the serene Western Ghats, Lion Safari at Tyavarekoppa, the biodiversity hotspot of Agumbe rainforest (one of the wettest places in India), and beautiful nature camps make this a paradise for nature enthusiasts.', category: 'Nature Hub', highlights: ['Jog Falls', 'Koodigudde Nature Camp', 'Lion Safari Tyavarekoppa', 'Agumbe Rainforest', 'Kundadri Hills', 'Sharavathi Valley'], bestTime: 'Jul - Jan', duration: '2-3 Days', emoji: '🌿' },
    { name: 'Udupi', slug: 'udupi', desc: 'Famous for the ancient Udupi Sri Krishna Temple established by the 13th-century saint Madhwacharya, and its legendary vegetarian cuisine — the Udupi restaurant chain serves millions daily across India. The coastal town boasts pristine beaches like Malpe, the unique hexagonal basalt rock formations at St. Mary\'s Island (accessible only by boat), and the prestigious Manipal University nearby.', category: 'Temple Town', highlights: ['Sri Krishna Temple', 'Malpe Beach', 'St. Mary\'s Island', 'Manipal University', 'Kaup Beach Lighthouse', 'Anantheshwara Temple'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🛕' },
    { name: 'Kolar', slug: 'kolar', desc: 'Historic city known for the magnificent Kotilingeshwara Temple with over one million Shiva lingas — one of the largest collections in the world. The golden mines of Kolar Gold Fields (KGF), once among the deepest gold mines in the world, have a fascinating colonial-era legacy. The cave temple of Antaragange, with its natural spring emerging from underground caves, and the ancient Kolaramma Temple add to Kolar\'s spiritual significance.', category: 'Historic City', highlights: ['Kotilingeshwara Temple', 'Kolar Gold Fields', 'Antaragange', 'Kolaramma Temple', 'Someshwara Temple', 'Bangarpet'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Mandya', slug: 'mandya', desc: 'Known as the "Sugar Bowl of Karnataka" with vast sugarcane fields stretching to the horizon. The crown jewel is the Krishna Raja Sagara (KRS) Dam across the Kaveri River and the magnificent Brindavan Gardens with its musical fountain — one of the most visited gardens in India. The nearby Ranganthittu Bird Sanctuary (home to thousands of migratory birds) and the spectacular Shivanasamudra Falls make Mandya a must-visit destination.', category: 'Agricultural Hub', highlights: ['KRS Dam', 'Brindavan Gardens', 'Ranganthittu Bird Sanctuary', 'Shivanasamudra Falls', 'Cauvery River', 'Melukote Temple'], bestTime: 'Jul - Jan', duration: '1-2 Days', emoji: '🌾' },
    { name: 'Tumakuru (Tumkur)', slug: 'tumakuru', desc: 'A rapidly growing industrial and educational city known for the beautiful Devarayana Durga hills with ancient hilltop temples, the revered Siddaganga Mutt (an important educational institution), the mysterious Namada Chilume (a natural spring believed to be created by Lord Rama), and the adventurous Makalidurga night trek. The city serves as a gateway to the scenic Western Ghats mountain ranges.', category: 'Industrial City', highlights: ['Devarayana Durga', 'Siddaganga Mutt', 'Namada Chilume', 'Makalidurga Trek', 'Kunigal Stud Farm', 'Goravanahalli Lakshmi Temple'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Bidar', slug: 'bidar', desc: 'Ancient city with the magnificent Bidar Fort — one of the most formidable medieval forts in India, featuring Islamic architecture, royal palaces, and mosques within its massive walls. The city is renowned worldwide for its unique Bidriware metal handicrafts — intricate silver inlay work on blackened zinc. The beautiful Bahmani and Baridi tombs, Guru Nanak Jhira (a sacred Sikh shrine with natural spring water), and the Narasimha Jhira Cave temple make Bidar a heritage treasure.', category: 'Historic City', highlights: ['Bidar Fort', 'Guru Nanak Jhira', 'Bahmani Tombs', 'Narasimha Jhira Cave', 'Bidriware Handicrafts', 'Chaubara Clock Tower'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Bijapur (Vijayapura)', slug: 'bijapur', desc: 'Treasure house of Islamic architecture with the iconic Gol Gumbaz — the second largest dome in the world (after St. Peter\'s Basilica) with its famous Whispering Gallery where even a whisper can be heard across 38 meters. The stunning Ibrahim Rauza (often called the Taj Mahal of the South), the massive Malik-e-Maidan cannon (one of the largest medieval cannons), and numerous beautiful mosques from the Adil Shahi dynasty make Bijapur an architectural paradise.', category: 'Heritage City', highlights: ['Gol Gumbaz', 'Ibrahim Rauza', 'Jama Masjid', 'Malik-e-Maidan Cannon', 'Bara Kaman', 'Upri Buruj'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Raichur', slug: 'raichur', desc: 'Ancient city on the banks of the Tungabhadra River with a massive hilltop fort that has witnessed the rise and fall of empires — from the Chalukyas to the Vijayanagara kings and the Nizams of Hyderabad. The Ek Minar Ki Masjid, the grand Jama Masjid, and the ancient Markandeshwara Temple reflect the city\'s rich multi-religious heritage. An important gateway between Karnataka and Andhra Pradesh.', category: 'Historic City', highlights: ['Raichur Fort', 'Ek Minar Ki Masjid', 'Jama Masjid', 'Markandeshwara Temple', 'Hammira Fort', 'Navanagar'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🏛️' },
    { name: 'Adoni', slug: 'adoni', desc: 'Historic city known for the massive Adoni Fort perched on a granite hill, one of the largest forts in the Deccan plateau with a network of underground passages. The ancient Rajoleswara Temple, the historic Jumma Masjid, and the sacred Ramatalai Temple reflect the city\'s rich heritage. Adoni was once a prosperous trading center under the Vijayanagara Empire and showcases a charming blend of Telugu and Kannada cultures.', category: 'Fort City', highlights: ['Adoni Fort', 'Rajoleswara Temple', 'Jumma Masjid', 'Ramatalai Temple', 'Underground Passages', 'Dargah Hazrat Shah'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🏰' },
    { name: 'Guntakal', slug: 'guntakal', desc: 'Major railway junction of South India connecting Karnataka, Andhra Pradesh, and other regions. An important transit hub for travelers exploring the Deccan plateau and the Rayalaseema region. The nearby Mukundra Hills offer scenic beauty and spiritual sites, while the British-era railway architecture and the ancient Karna Temple add to the town\'s unique character as a gateway to both states.', category: 'Railway Hub', highlights: ['Railway Junction', 'Mukundra Hills', 'Karna Temple', 'British-era Architecture', 'Tungabhadra Access', 'Bellary Gateway'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🚂' },
    { name: 'Bhadravati', slug: 'bhadravati', desc: 'Industrial town on the banks of the Bhadra River, home to the historic Visvesvaraya Iron and Steel Plant established in 1923 by Sir M. Visvesvaraya. The town is surrounded by lush green forests and is close to the wildlife-rich Bhadra Tiger Reserve — one of the best places in Karnataka to spot tigers, elephants, and diverse wildlife in their natural habitat. The Lakshmi Narasimha Temple adds spiritual charm.', category: 'Industrial City', highlights: ['Bhadra Dam', 'Bhadra Wildlife Sanctuary', 'Vishweshwaraiah Museum', 'Lakshmi Narasimha Temple', 'IGL Steel Plant', 'Bhadra River'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
  ],
};

export const KERALA: StateData = {
  name: 'Kerala', slug: 'kerala', coverImg: '/states/kerala-cover.jpg',
  tagline: "God's Own Country", tagColor: 'text-cyan-400', icon: '🛶', accentColor: 'cyan',
  heroDesc: 'Backwaters of Alleppey, tea gardens of Munnar, wildlife of Thekkady, beaches of Kovalam — experience paradise on earth.',
  places: [
    { name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', desc: 'The capital city of Kerala, home to the iconic Sri Padmanabhaswamy Temple — the world\'s richest religious institution with treasures worth billions. Beautiful Kovalam Beach with its crescent-shaped shoreline, the historic Napier Museum and Zoological Garden, the majestic Kanakakunnu Palace, and the serene Veli Tourist Village where the lake meets the Arabian Sea make this city a perfect blend of heritage, culture, and tropical beauty.', category: 'Capital City', highlights: ['Padmanabhaswamy Temple', 'Kovalam Beach', 'Napier Museum', 'Veli Tourist Village', 'Kanakakunnu Palace', 'Shanghumukham Beach'], bestTime: 'Sep - Mar', duration: '2-3 Days', emoji: '🏙️' },
    { name: 'Kochi', slug: 'kochi', desc: 'Queen of the Arabian Sea and Kerala\'s commercial capital. Famous for the iconic Chinese Fishing Nets — a legacy of ancient trade with China, the beautiful Dutch Palace with its Ramayana murals, the 1568 Jewish Synagogue (oldest in the Commonwealth), the charming Fort Kochi heritage zone with its colonial buildings and street art, vibrant Marine Drive promenade, and a thriving arts, culinary, and shopping scene with incredible seafood.', category: 'Metro City', highlights: ['Chinese Fishing Nets', 'Fort Kochi', 'Jewish Synagogue', 'Marine Drive', 'Dutch Palace', 'Bolghatty Palace'], bestTime: 'Sep - Mar', duration: '2-3 Days', emoji: '🏙️' },
    { name: 'Kozhikode', slug: 'kozhikode', desc: 'Historic city where Portuguese explorer Vasco da Gama first landed in India in 1498. Known as the spice capital of Kerala, famous for its unique Malabar cuisine — from the legendary Kozhikode biryani to the sweet Kozhikode halwa and banana chips. The beautiful Kozhikode Beach, historic Kappad Beach (Gama\'s landing spot), the charming Mananchira Square, and the famous SM Street (Sweet Meat Street) for shopping.', category: 'Historic City', highlights: ['Kozhikode Beach', 'Kappad Beach', 'Mananchira Square', 'Sweet Street', 'Beypore Shipyard', 'Kadalundi Bird Sanctuary'], bestTime: 'Sep - Mar', duration: '2 Days', emoji: '🏙️' },
    { name: 'Alappuzha', slug: 'alappuzha', desc: 'The Venice of the East — famous worldwide for its enchanting backwater houseboat cruises through a network of serene canals, lagoons, and lakes. The thrilling Nehru Trophy Snake Boat Race held every August draws hundreds of thousands of spectators. Nearby Kumarakom Bird Sanctuary on Vembanad Lake is a paradise for birdwatchers, while the beautiful Marari Beach offers peaceful coastal relaxation away from the crowds.', category: 'Backwaters', highlights: ['Houseboat Cruises', 'Nehru Trophy Boat Race', 'Kumarakom', 'Marari Beach', 'Vembanad Lake', 'Pathiramanal Island'], bestTime: 'Sep - Mar', duration: '2-3 Days', emoji: '🛶' },
    { name: 'Kollam', slug: 'kollam', desc: 'Gateway to the famous Kerala backwaters and the starting point of the scenic Ashtamudi Lake houseboat cruises — Kerala\'s second largest lake shaped like eight arms. Known for cashew processing, ancient Thangassery Lighthouse built by the British in 1902, the spectacular Jatayu Earth Center featuring the world\'s largest bird sculpture, and beautiful backwater villages that showcase authentic Kerala life.', category: 'Backwaters', highlights: ['Ashtamudi Lake', 'Thangassery Lighthouse', 'Jatayu Earth Center', 'Backwater Cruises', 'Thenmala Ecotourism', 'Palaruvi Falls'], bestTime: 'Sep - Mar', duration: '2 Days', emoji: '🛶' },
    { name: 'Munnar', slug: 'munnar', desc: 'One of India\'s most beautiful hill stations at 1,600 meters elevation, with endless tea gardens carpeting rolling hills as far as the eye can see. The misty Eravikulam National Park is home to the endangered Nilgiri Tahr, while Mattupetty Dam offers boating amid stunning scenery. The Kolukkumalai Tea Estate — the highest tea plantation in the world — and Top Station viewpoint with views stretching to the neighboring state make Munnar truly magical.', category: 'Hill Station', highlights: ['Tea Gardens', 'Eravikulam National Park', 'Mattupetty Dam', 'Top Station', 'Kolukkumalai', 'Echo Point'], bestTime: 'Sep - May', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Kannur', slug: 'kannur', desc: 'Land of Theyyam — Kerala\'s most mystical and ancient ritual art form where performers embody divine spirits in elaborate costumes and face paint. Famous for pristine beaches like Payyambalam and Muzhappilangad (India\'s longest drive-in beach), the historic St. Angelo Fort built by the Portuguese in 1505, ancient handloom weaving traditions producing world-famous Kannur cotton, and the beautiful Arakkal Museum showcasing Kerala\'s only Muslim royal family.', category: 'Coastal City', highlights: ['Theyyam Ritual', 'Payyambalam Beach', 'St. Angelo Fort', 'Muzhappilangad Beach', 'Arakkal Museum', 'Parassinikkadavu Temple'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🏖️' },
    { name: 'Thrissur', slug: 'thrissur', desc: 'Cultural capital of Kerala and home to the spectacular Thrissur Pooram — the greatest temple festival in Kerala, featuring decorated elephants, traditional percussion ensembles (Panchavadyam), and a magnificent fireworks display that draws millions. The sacred Guruvayur Sree Krishna Temple, Kerala Kalamandalam (premier performing arts institution), Vadakkumnathan Temple with its classical Kerala architecture, and the vibrant Swaraj Round make Thrissur the cultural heartbeat of Kerala.', category: 'Cultural Capital', highlights: ['Thrissur Pooram', 'Guruvayur Temple', 'Vadakkumnathan Temple', 'Kalamandalam', 'Athirapally Falls', 'Peechi Dam'], bestTime: 'Sep - Mar', duration: '2-3 Days', emoji: '🎭' },
    { name: 'Palakkad', slug: 'palakkad', desc: 'The granary of Kerala with vast green paddy fields stretching to the horizon. The stunning Palakkad Gap — a 32-kilometer pass through the Western Ghats — creates a unique microclimate that makes this region exceptionally fertile. The beautiful Malampuzha Dam with its rock garden, rope way, and aquarium, the pristine Silent Valley National Park (one of the last undisturbed stretches of South Western Ghats tropical evergreen forests), and the ancient Jainmedu Temple make Palakkad special.', category: 'Gateway to Kerala', highlights: ['Palakkad Gap', 'Malampuzha Dam', 'Silent Valley NP', 'Jainmedu Temple', 'Nelliampathy Hills', 'Parambikulam Tiger Reserve'], bestTime: 'Sep - Mar', duration: '2 Days', emoji: '🌿' },
    { name: 'Kasaragod', slug: 'kasaragod', desc: 'Northernmost district of Kerala known for the magnificent Bekal Fort — Kerala\'s largest and best-preserved fort, rising 130 feet above the Arabian Sea with stunning panoramic views. Pristine beaches, rich folk art forms like Theyyam and Yakshagana, the beautiful Chandragiri River, and the lush Ranipuram Hills offering trekking opportunities through forest trails make Kasaragod an offbeat gem waiting to be discovered.', category: 'Coastal Town', highlights: ['Bekal Fort', 'Bekal Beach', 'Chandragiri Fort', 'Ranipuram Hills', 'Ananthapura Lake Temple', 'Kottancheri Hills'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🏖️' },
    { name: 'Vadakara', slug: 'vadakara', desc: 'Historic coastal town and the birthplace of the legendary warrior Thacholi Othenan, celebrated in the famous Vadakkanpattukal (Northern Ballads of Kerala). Famous for beautiful beaches, the ancient Lokanarkavu Temple associated with the warrior traditions, and the unique martial art culture of Kalarippayattu — one of the oldest fighting systems in the world with training centers that attract international martial arts enthusiasts.', category: 'Coastal Town', highlights: ['Lokanarkavu Temple', 'Kozhikode Beach', 'Kalarippayattu Centers', 'Vatakara Fort', 'Sand Banks Beach', 'Velliyamkallu'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏖️' },
    { name: 'Malappuram', slug: 'malappuram', desc: 'Rich in cultural heritage with beautiful hill stations, historic mosques, and lush green landscapes. The lush Kadalundi Bird Sanctuary at the estuary of the Kadalundi River is a haven for migratory birds. The Nilambur Teak Museum showcases Kerala\'s historic teak plantations, while Kottakkunnu offers beautiful sunset views. Known as the land of great poets and the birthplace of Malayalam literature.', category: 'Cultural Town', highlights: ['Kadalundi Bird Sanctuary', 'Nilambur Teak Museum', 'Kottakkunnu', 'Tanur Beach', 'Angadipuram Temple', 'Nedumkayam'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🎭' },
    { name: 'Kottayam', slug: 'kottayam', desc: 'The land of latex, letters, and lakes — known as the literary capital of Kerala with a 100% literacy rate. Famous for the beautiful Vembanad Lake backwaters, lush rubber plantations, ancient churches including the 450-year-old St. Mary\'s Church (Valiyapally), the stunning Kumarakom Bird Sanctuary, and the beautiful Ettumanoor Mahadeva Temple with its exquisite Dravidian murals and the legendary Ezharaponnana (seven and a half elephants) offering.', category: 'Backwaters', highlights: ['Vembanad Lake', 'Kumarakom Bird Sanctuary', 'Ettumanoor Temple', 'Rubber Plantations', 'St. Mary\'s Church', 'Ilaveezhapoonchira'], bestTime: 'Sep - Mar', duration: '2 Days', emoji: '🛶' },
  ],
};

export const TAMIL_NADU: StateData = {
  name: 'Tamil Nadu', slug: 'tamilnadu', coverImg: '/states/tamilnadu-cover.jpg',
  tagline: 'Temple Heritage', tagColor: 'text-purple-400', icon: '🛕', accentColor: 'purple',
  heroDesc: 'Ancient temples, hill stations, French colonies, and pristine beaches — experience the cultural heart of South India.',
  places: [
    { name: 'Chennai', slug: 'chennai', desc: 'India\'s cultural capital and gateway to South India. Home to the world\'s second longest urban beach — Marina Beach stretching 13 kilometers along the Bay of Bengal. Stunning temples like the colorful Kapaleeshwarar Temple in Mylapore, British-era Fort St. George (first British fortress in India), the Gothic San Thome Basilica built over the tomb of St. Thomas the Apostle, vibrant arts scene, and the famous South Indian film industry (Kollywood).', category: 'Capital City', highlights: ['Marina Beach', 'Kapaleeshwarar Temple', 'Fort St. George', 'San Thome Basilica', 'Guindy National Park', 'Valluvar Kottam'], bestTime: 'Nov - Feb', duration: '2-3 Days', emoji: '🏙️' },
    { name: 'Madurai', slug: 'madurai', desc: 'One of India\'s oldest continuously inhabited cities (over 2,500 years), home to the spectacular Meenakshi Amman Temple with its towering gopurams covered in thousands of exquisitely detailed colorful sculptures of gods, goddesses, and mythical creatures. The grand Thirumalai Nayak Palace with its massive pillars and celestial decorations, the Gandhi Museum, and the sacred Vaigai River flowing through the heart of the city make Madurai the cultural soul of Tamil Nadu.', category: 'Temple City', highlights: ['Meenakshi Amman Temple', 'Thirumalai Nayak Palace', 'Gandhi Museum', 'Vaigai River', 'Thiruparankundram Temple', 'Alagar Koyil'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🛕' },
    { name: 'Coimbatore', slug: 'coimbatore', desc: 'The Manchester of South India — a major textile and manufacturing hub nestled at the foothills of the Western Ghats. Known as the gateway to popular hill stations Ooty and Valparai, with excellent educational institutions, beautiful temples like the ancient Marudhamalai Murugan Temple perched on a hill, the scenic Siruvani Waterfalls known for its sweet-tasting water, and the famous Black Thunder water theme park.', category: 'Metro City', highlights: ['Marudhamalai Temple', 'Siruvani Waterfalls', 'VOC Park', 'Black Thunder', 'Ooty Gateway', 'Adiyogi Shiva Statue'], bestTime: 'Sep - Feb', duration: '2 Days', emoji: '🏙️' },
    { name: 'Ooty', slug: 'ooty', desc: 'Queen of the Nilgiris and one of India\'s most beloved hill stations at 2,240 meters elevation. Famous for the charming toy train ride through 16 tunnels and 250 bridges on the Nilgiri Mountain Railway (UNESCO World Heritage), the beautiful Government Botanical Garden with 1,000+ plant species, boating on the serene Ooty Lake, and the breathtaking Dodabetta Peak — highest point in the Nilgiris offering panoramic views of three states.', category: 'Hill Station', highlights: ['Ooty Toy Train', 'Botanical Garden', 'Dodabetta Peak', 'Ooty Lake', 'Coonoor', 'Rose Garden'], bestTime: 'Apr - Jun, Sep - Nov', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Rameswaram', slug: 'rameswaram', desc: 'One of the holiest pilgrimage sites in India and one of the four sacred Char Dham sites. Home to the Ramanathaswamy Temple with the world\'s longest temple corridor — 1,220 meters with 1,212 ornate pillars. The engineering marvel Pamban Bridge (India\'s first sea bridge) connecting the island to mainland India over the turquoise waters. The mystical Dhanushkodi — a ghost town destroyed by the 1964 cyclone — and the sacred Agni Theertham where pilgrims perform rituals make Rameswaram deeply spiritual.', category: 'Pilgrimage', highlights: ['Ramanathaswamy Temple', 'Pamban Bridge', 'Dhanushkodi Ghost Town', 'Agni Theertham', 'APJ Abdul Kalam Memorial', 'Five-faced Hanuman Temple'], bestTime: 'Oct - Apr', duration: '2 Days', emoji: '🛕' },
    { name: 'Kanyakumari', slug: 'kanyakumari', desc: 'The southernmost tip of mainland India where three great water bodies — the Arabian Sea, Bay of Bengal, and Indian Ocean — dramatically converge. Famous for the Vivekananda Rock Memorial accessible by ferry, where Swami Vivekananda meditated, the towering 133-foot Thiruvalluvar Statue on a neighboring island, the breathtaking sunrise and sunset views (unique for watching both from the same point), and the beautiful Gandhi Memorial built where his ashes were kept before immersion.', category: 'Coastal Town', highlights: ['Vivekananda Rock Memorial', 'Thiruvalluvar Statue', 'Sunrise Point', 'Gandhi Memorial', 'Suchindram Temple', 'Padmanabhapuram Palace'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🌅' },
    { name: 'Pondicherry', slug: 'pondicherry', desc: 'A charming former French colony with colorful colonial-era buildings, tree-lined boulevards, French cafes and bakeries serving authentic croissants and espresso, the famous Sri Aurobindo Ashram, the utopian Auroville Township with its golden Matrimandir meditation sphere, and a unique Franco-Tamil cultural blend visible in the architecture, cuisine, and lifestyle. The Promenade Beach, Auroville Beach, and the vibrant French Quarter make Pondicherry unlike any other Indian city.', category: 'French Colony', highlights: ['Promenade Beach', 'Auroville', 'French Quarter', 'Sri Aurobindo Ashram', 'Paradise Beach', 'Matrimandir'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏘️' },
    { name: 'Tiruchirapalli', slug: 'trichy', desc: 'Home to the iconic Rock Fort Temple perched dramatically on an 83-meter-high ancient rock — one of the oldest rock formations in the world at 3.8 billion years. The massive Srirangam Temple island complex is the largest functioning Hindu temple in the world. The stunning Jambukeswarar Temple (one of the five Pancha Bhoota Stalas representing water), the ancient Kallanai Dam (built 2,000 years ago — one of the oldest water-diversion structures still in use), and the beautiful Mukkombu make Trichy extraordinary.', category: 'Temple City', highlights: ['Rock Fort Temple', 'Srirangam Temple', 'Jambukeswarar Temple', 'Kallanai Dam', 'Mukkombu', 'St. Joseph\'s Church'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🛕' },
    { name: 'Thanjavur', slug: 'thanjavur', desc: 'The rice bowl of Tamil Nadu and home to the magnificent Brihadeeswara Temple — a UNESCO World Heritage Site completed in 1010 AD by Rajaraja Chola. Its 66-meter vimana (tower) was the tallest in India for centuries. Famous for the exquisite Tanjore paintings (gold-leaf artwork), classical music and dance traditions, the grand Maratha Palace complex housing the Saraswathi Mahal Library with rare ancient manuscripts, and the beautiful Schwartz Church.', category: 'Heritage City', highlights: ['Brihadeeswara Temple', 'Tanjore Palace', 'Saraswathi Mahal Library', 'Tanjore Paintings', 'Schwartz Church', 'Punniyamurthi Temple'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Kodaikanal', slug: 'kodaikanal', desc: 'Princess of Hill Stations — a beautiful mountain retreat at 2,133 meters in the Palani Hills. The star-shaped Kodaikanal Lake with rowboats and cycling paths, the scenic Coaker\'s Walk — a 1-km paved path along the cliff edge offering breathtaking valley views, Bryant Park with its rare flowering plants, Silver Cascade Falls, the misty Pine Forest with towering trees, and the beautiful Pillar Rocks are natural wonders that make Kodaikanal a perfect romantic getaway.', category: 'Hill Station', highlights: ['Kodaikanal Lake', 'Coaker\'s Walk', 'Pine Forest', 'Silver Cascade Falls', 'Pillar Rocks', 'Guna Caves'], bestTime: 'Apr - Jun, Sep - Oct', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Mahabalipuram', slug: 'mahabalipuram', desc: 'UNESCO World Heritage Site with stunning 7th-century Pallava rock-cut temples and shore temples. The Five Rathas — monolithic rock temples carved from single boulders, each shaped like a different chariot — showcase extraordinary craftsmanship. The magnificent Arjuna\'s Penance — the world\'s largest bas-relief measuring 27m x 9m carved on a single rock face, the beautiful Shore Temple standing dramatically against the Bay of Bengal, and the golden Mahabalipuram Beach make this an archaeologist\'s paradise.', category: 'Heritage', highlights: ['Shore Temple', 'Five Rathas', 'Arjuna\'s Penance', 'Mahabalipuram Beach', 'Krishna\'s Butter Ball', 'Tiger\'s Cave'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Vellore', slug: 'vellore', desc: 'Known for the magnificent Golden Temple (Sripuram) — a stunning spiritual park with a temple covered in 1.5 tons of pure gold foil, set amid beautifully landscaped gardens and a star-shaped path. The historic 16th-century Vellore Fort built by the Vijayanagara kings, the ancient Jalakandeswarar Temple inside the fort with its stunning Dravidian architecture, and the prestigious VIT University make Vellore a unique blend of spiritual grandeur, heritage, and education.', category: 'Temple City', highlights: ['Golden Temple Sripuram', 'Vellore Fort', 'Jalakandeswarar Temple', 'VIT University', 'Amirthi Zoological Park', 'Yelagiri Hills'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🛕' },
    { name: 'Salem', slug: 'salem', desc: 'A major city surrounded by beautiful hills and known as the Steel City of Tamil Nadu. Gateway to the stunning Yercaud hill station at 1,515 meters — called the Poor Man\'s Ooty — with its beautiful Yercaud Lake, Killiyur Falls, and Lady\'s Seat viewpoint. Famous for mango orchards producing some of India\'s finest mangoes, the picturesque Mettur Dam, the ancient Kailasanathar Temple, and the 1008 Lingam Temple at Poiman Karadu.', category: 'Industrial City', highlights: ['Yercaud Hill Station', 'Mettur Dam', 'Kailasanathar Temple', 'Mango Orchards', '1008 Lingam Temple', 'Kurumbapatti Zoo'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🏙️' },
    { name: 'Tirunelveli', slug: 'tirunelveli', desc: 'Ancient temple city famous for the magnificent Nellaiappar Temple complex dedicated to Lord Shiva, with its musical pillars that produce the seven notes of Indian classical music. The spectacular Courtallam Falls — known as the Spa of South India — features nine waterfalls where the Western Ghats streams cascade from varying heights, believed to have medicinal properties. The legendary Tirunelveli halwa, made with ghee and wheat milk, has been a culinary icon for over a century.', category: 'Temple City', highlights: ['Courtallam Falls', 'Nellaiappar Temple', 'Tirunelveli Halwa', 'Manimuthar Falls', 'Papanasam Temple', 'Agasthiyar Falls'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🛕' },
    { name: 'Tiruppur', slug: 'tiruppur', desc: 'The knitwear capital of India, producing garments for global brands like Nike, Adidas, and H&M. A rapidly growing industrial city that exports textiles worth billions worldwide. Despite its industrial focus, Tiruppur has beautiful temples like the ancient Avinashiappar Temple, the scenic Noyyal River, and serves as a gateway to the beautiful Annamalai hills and the stunning Palani Murugan Temple — one of the six abodes of Lord Murugan.', category: 'Industrial City', highlights: ['Textile Industry', 'Noyyal River', 'Avinashi Temple', 'Palani Temple Access', 'Amaravathi Dam', 'Thirumoorthy Hills'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Dindigul', slug: 'dindigul', desc: 'Known for the mighty Dindigul Fort perched atop a 280-meter rock hill, built by the Madurai Nayak kings and later strengthened by Hyder Ali and Tipu Sultan. Famous across South India for the delicious Dindigul biryani — cooked with seeraga samba rice and unique spice blends. Gateway to the beautiful Kodaikanal hill station, the lush Sirumalai Hills with their banana plantations, and ancient temples like the Abirami Amman Temple.', category: 'Industrial City', highlights: ['Dindigul Fort', 'Kodaikanal Gateway', 'Sirumalai Hills', 'Dindigul Biryani', 'Natham Hill', 'Kamarajar Lake'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Pollachi', slug: 'pollachi', desc: 'A charming town known as the coconut capital of Tamil Nadu, surrounded by lush coconut, areca nut, and sugarcane plantations. Famous as the gateway to Topslip in the Anamalai Tiger Reserve — one of the best places in South India for wildlife spotting including elephants, tigers, and the endangered lion-tailed macaque. The beautiful Aliyar Dam with its park and garden, the Masani Amman Temple, and the scenic Valparai hill road with its 40 hairpin bends make Pollachi a nature lover\'s paradise.', category: 'Nature Town', highlights: ['Topslip Tiger Reserve', 'Anaimalai Hills', 'Aliyar Dam', 'Masani Amman Temple', 'Valparai Hill Road', 'Monkey Falls'], bestTime: 'Oct - Mar', duration: '2 Days', emoji: '🌿' },
    { name: 'Kumbakonam', slug: 'kumbakonam', desc: 'Temple town of Tamil Nadu with over 188 temples within the city limits, making it one of the most temple-dense cities in the world. Famous as the location for the sacred Kumbh Mela (Mahamaham) held every 12 years when millions of pilgrims bathe in the Mahamaham Tank. The magnificent Airavatesvara Temple at nearby Darasuram is a UNESCO World Heritage Site with exquisite Chola architecture. The city is also legendary for its Kumbakonam Degree Coffee — one of India\'s finest filter coffees.', category: 'Temple Town', highlights: ['Airavatesvara Temple (UNESCO)', 'Mahamaham Tank', 'Sarangapani Temple', 'Kumbakonam Coffee', 'Adi Kumbeswarar Temple', 'Darasuram Temple'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🛕' },
    { name: 'Karaikudi', slug: 'karaikudi', desc: 'The cultural capital of the Chettinad region, famous for the magnificent Chettiar mansions — sprawling palatial homes built by the wealthy Nattukottai Chettiars with stunning Athangudi handmade tiles, Burmese teak pillars, Italian marble, and Belgian glass. The Chettinad cuisine is considered one of India\'s finest culinary traditions — spicy, aromatic, and unforgettable. The Kanadukathan Palace, antique markets selling Chettinad artifacts, and beautiful temples make Karaikudi a heritage lover\'s dream.', category: 'Heritage Town', highlights: ['Chettinad Mansions', 'Chettinad Cuisine', 'Athangudi Tiles', 'Kanadukathan Palace', 'Chettinad Palace', 'Antique Markets'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Tiruvannamalai', slug: 'tiruvannamalai', desc: 'Home to the sacred Arunachaleswarar Temple — one of the largest temple complexes in India, dedicated to Lord Shiva who manifested here as a column of fire (Agni Lingam). The holy Annamalai Hill (2668 feet) is considered a manifestation of Lord Shiva himself, and the full moon Girivalam (14-km circumambulation around the hill) draws hundreds of thousands of pilgrims every month. The great sage Ramana Maharshi lived and taught at the peaceful Ramana Ashram, attracting spiritual seekers from around the world.', category: 'Pilgrimage', highlights: ['Arunachaleswarar Temple', 'Annamalai Hill', 'Ramana Ashram', 'Girivalam', 'Skandashramam', 'Seshadri Swamigal Ashram'], bestTime: 'Nov - Feb', duration: '2 Days', emoji: '🛕' },
    { name: 'Sivakasi', slug: 'sivakasi', desc: 'The fireworks capital of India and a major printing and matchbox manufacturing hub, producing 90% of India\'s fireworks, 60% of safety matches, and a significant portion of printed materials. Known as Little Japan for its industrial prowess and work ethic, this small town in Virudhunagar district has an outsized impact on celebrations across India. The nearby Ayyanar Falls in the scenic Western Ghats and the ancient Srivilliputhur Andal Temple (one of the 108 Divya Desams) offer natural and spiritual respite.', category: 'Industrial Town', highlights: ['Fireworks Industry', 'Printing Industry', 'Ayyanar Falls', 'Srivilliputhur Temple', 'Matchbox Factories', 'Grizzled Squirrel Sanctuary'], bestTime: 'Oct - Mar', duration: '1 Day', emoji: '🎆' },
    { name: 'Tuticorin (Thoothukudi)', slug: 'tuticorin', desc: 'Major port city and pearl fishing center on the Gulf of Mannar, known as the Pearl City of India for its historic pearl diving tradition. The beautiful Roche Park, the historic Our Lady of Snows Basilica — one of South India\'s largest churches, the scenic Beach Road, and a thriving salt production industry make Tuticorin unique. The city is also a gateway to the beautiful Gulf of Mannar Marine National Park with its rich coral reefs and marine biodiversity.', category: 'Coastal City', highlights: ['Pearl Fishing', 'Our Lady of Snows Basilica', 'Roche Park', 'Beach Road', 'Gulf of Mannar Marine NP', 'Harbour View'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🏖️' },
    { name: 'Nagercoil', slug: 'nagercoil', desc: 'A beautiful town near Kanyakumari known for its pleasant climate, lush green paddy fields, ancient temples, and the famous Nagaraja Temple dedicated to the serpent god — unique in Tamil Nadu. Gateway to the hill stations of Kanyakumari district including the beautiful Thirparappu Falls. The nearby Padmanabhapuram Palace — a magnificent 16th-century wooden palace of the Travancore kings — is considered the finest example of traditional Kerala architecture in existence.', category: 'Temple Town', highlights: ['Nagaraja Temple', 'Suchindram Temple', 'Padmanabhapuram Palace', 'Vattakottai Fort', 'Thirparappu Falls', 'Udayagiri Fort'], bestTime: 'Oct - Mar', duration: '1-2 Days', emoji: '🛕' },
  ],
};

export const ANDHRA: StateData = {
  name: 'Andhra Pradesh', slug: 'andhra', coverImg: '/states/andhra-cover.jpg',
  tagline: 'Pilgrimage & Nature', tagColor: 'text-orange-400', icon: '⛰️', accentColor: 'orange',
  heroDesc: 'Sacred temples of Tirupati, stunning Araku Valley coffee hills, pristine Visakhapatnam beaches, and the historic Amaravati Stupa.',
  places: [
    { name: 'Tirupathi', slug: 'tirupathi', desc: 'Home to the world-famous Sri Venkateswara Temple on the seven sacred hills of Tirumala — the most visited and richest religious center in the world with over 50,000 pilgrims visiting daily and annual offerings exceeding thousands of crores. The sacred Sri Padmavathi Temple in Tiruchanoor, the mystical Akasaganga Theertham (natural spring on the hill), and the rare natural rock arch Silathoranam make Tirupati the most important pilgrimage destination in South India.', category: 'Pilgrimage', highlights: ['Tirumala Venkateswara Temple', 'Sri Padmavathi Temple', 'Akasaganga Theertham', 'Silathoranam', 'TTD Gardens', 'Sri Govindarajaswami Temple'], bestTime: 'Sep - Feb', duration: '1-2 Days', emoji: '🛕' },
    { name: 'Visakhapatnam', slug: 'visakhapatnam', desc: 'The City of Destiny — Andhra\'s largest city and a major port on the Bay of Bengal. Famous for beautiful beaches like RK Beach and Ramakrishna Beach, the fascinating Submarine Museum (only one in India), the stunning Kailasagiri Hill Park with its ropeway and panoramic ocean views, the ancient Simhachalam Temple, and as the gateway to the beautiful Araku Valley and Borra Caves in the Eastern Ghats.', category: 'Coastal City', highlights: ['RK Beach', 'Kailasagiri Park', 'Submarine Museum', 'Simhachalam Temple', 'Araku Valley Access', 'Rushikonda Beach'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏖️' },
    { name: 'Vijayawada', slug: 'vijayawada', desc: 'The business capital of Andhra Pradesh, strategically located on the banks of the Krishna River. The sacred Kanaka Durga Temple perched atop Indrakeeladri Hill offers panoramic views of the city and river. The impressive Prakasam Barrage spanning the Krishna, the beautiful Bhavani Island (one of the largest river islands), the ancient Mogalarajapuram Caves, and the bustling Kondapalli Fort with its famous lightweight toys make Vijayawada a vibrant city.', category: 'Capital Region', highlights: ['Kanaka Durga Temple', 'Prakasam Barrage', 'Bhavani Island', 'Mogalarajapuram Caves', 'Kondapalli Fort', 'Undavalli Caves'], bestTime: 'Oct - Feb', duration: '2 Days', emoji: '🏙️' },
    { name: 'Amaravati', slug: 'amaravati', desc: 'The new capital of Andhra Pradesh and one of ancient India\'s greatest Buddhist centers. The famous Amaravati Stupa — built during the Satavahana dynasty around 200 BCE — was once the grandest Buddhist monument in India with exquisite limestone relief carvings now housed in museums worldwide. The magnificent 125-foot Dhyana Buddha statue, the ancient Amareswara Shiva Temple, and the emerging modern capital region make Amaravati a meeting point of ancient glory and future ambition.', category: 'Capital City', highlights: ['Amaravati Stupa', 'Dhyana Buddha', 'Amareswara Temple', 'Capital Region', 'Limestone Carvings', 'Buddhist Heritage'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🏛️' },
    { name: 'Araku Valley', slug: 'araku-valley', desc: 'A stunning hill station nestled at 911 meters in the Eastern Ghats, famous for its organic coffee plantations producing some of India\'s finest Arabica coffee. The Borra Caves — one of the largest cave formations in India with spectacular stalactites and stalagmites reaching up to 100 feet — are over 150 million years old. The beautiful tribal culture of the Araku and Borra tribes, the scenic Araku Valley train journey through 58 tunnels and 84 bridges, and the lush Padmapuram Botanical Gardens make Araku magical.', category: 'Hill Station', highlights: ['Borra Caves', 'Coffee Plantations', 'Tribal Museum', 'Araku Valley Railway', 'Padmapuram Gardens', 'Katiki Waterfalls'], bestTime: 'Oct - Mar', duration: '2-3 Days', emoji: '🏔️' },
    { name: 'Kurnool', slug: 'kurnool', desc: 'Historic city and the erstwhile capital of the Andhra State (1953-1956). Gateway to the incredible Belum Caves — the second largest cave system in India with 3.5 km of explored passages, stunning stalactite formations, and an underground stream. The magnificent Konda Reddy Fort with its underground tunnels, the sacred Mantralayam Raghavendra Swamy Temple (major pilgrimage center), and the beautiful Rollapadu Bird Sanctuary make Kurnool a destination of diverse wonders.', category: 'Historic City', highlights: ['Belum Caves', 'Konda Reddy Fort', 'Rollapadu Sanctuary', 'Mantralayam Temple', 'Nallamala Hills', 'Oravakallu Rock Garden'], bestTime: 'Oct - Feb', duration: '2 Days', emoji: '🏛️' },
    { name: 'Nellore', slug: 'nellore', desc: 'Coastal city on the banks of the sacred Penna River, famous for the ancient Ranganatha Temple — one of the tallest temple towers in Andhra Pradesh. The beautiful Mypadu Beach with golden sands, the Nelapattu Bird Sanctuary (one of the largest pelican habitats in Southeast Asia), the historic Pulicat Lake (second largest brackish water lagoon in India), and delicious Nellore cuisine including the famous Nellore chepala pulusu (fish curry) make this city special.', category: 'Coastal City', highlights: ['Ranganatha Temple', 'Mypadu Beach', 'Nelapattu Bird Sanctuary', 'Pulicat Lake', 'Udayagiri Fort', 'Penna River'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏖️' },
    { name: 'Guntur', slug: 'guntur', desc: 'A major city in the Amaravati capital region, known as the capital of Andhra cuisine — especially the world-famous Guntur chillies that define the heat and flavor of South Indian food. Home to the ancient Amaravati Buddhist heritage site, the magnificent Kondaveedu Fort ruins with panoramic views, the Uppalapadu Bird Sanctuary hosting thousands of migratory birds including spot-billed pelicans, and the vibrant Guntur chilli market — one of the largest in Asia.', category: 'Commercial City', highlights: ['Kondaveedu Fort', 'Amaravati Access', 'Uppalapadu Bird Sanctuary', 'Guntur Chilli Market', 'Bhattiprolu Stupa', 'Nagarjuna Sagar Access'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏙️' },
    { name: 'Rajahmundry', slug: 'rajahmundry', desc: 'Cultural capital of Andhra Pradesh on the sacred banks of the Godavari River — called the Dakshin Ganga (Ganges of the South). The iconic Godavari Bridge (Havelock Bridge), the stunning Papi Hills with their scenic boat cruises through lush green gorges, the lush Coringa mangrove forests (second largest mangrove forest in India), the sacred ISKCON Temple, and the famous Pushkaralu bathing ghats where millions of pilgrims gather every 12 years make Rajahmundry culturally rich.', category: 'Cultural City', highlights: ['Godavari Bridge', 'Papi Hills', 'Coringa Mangroves', 'ISKCON Temple', 'Damerla Rama Rao Art Gallery', 'Godavari River Cruises'], bestTime: 'Oct - Feb', duration: '2 Days', emoji: '🎭' },
    { name: 'Warangal', slug: 'warangal', desc: 'Ancient capital of the great Kakatiya dynasty (12th-14th century), home to the magnificent Warangal Fort with its iconic Kakatiya Kala Thoranam (gateway arch) — now the symbol of Telangana state. The stunning Thousand Pillar Temple built in 1163 AD, the breathtaking Ramappa Temple — a UNESCO World Heritage Site with floating bricks and intricate carvings, the beautiful Pakhal Lake, and the ancient Bhadrakali Temple make Warangal a treasure trove of medieval Indian architecture.', category: 'Heritage City', highlights: ['Warangal Fort', 'Thousand Pillar Temple', 'Ramappa Temple (UNESCO)', 'Kakatiya Kala Thoranam', 'Pakhal Lake', 'Bhadrakali Temple'], bestTime: 'Oct - Feb', duration: '2 Days', emoji: '🏛️' },
    { name: 'Ananthapur', slug: 'ananthapur', desc: 'The largest district in Andhra Pradesh, known worldwide as the home of Puttaparthi — birthplace and ashram of Sri Sathya Sai Baba that attracted millions of devotees from across the globe. The ancient Lepakshi Temple with its mind-boggling hanging pillar (which doesn\'t touch the ground), the largest Nandi bull monolith in India, exquisite Vijayanagara-era frescoes, and the beautiful Penna Ahobilam wildlife sanctuary make Ananthapur a spiritual and architectural marvel.', category: 'Spiritual Center', highlights: ['Puttaparthi Ashram', 'Lepakshi Temple', 'Hanging Pillar', 'Penna Ahobilam', 'Largest Nandi Monolith', 'Gooty Fort'], bestTime: 'Oct - Feb', duration: '2 Days', emoji: '🛕' },
    { name: 'Kadapa (Cuddapah)', slug: 'kadapa', desc: 'Historic city known for the breathtaking Gandikota Fort — called the Grand Canyon of India — where the Penna River has carved a stunning gorge over 300 feet deep through massive red granite rocks, creating landscape views rivaling the Arizona Grand Canyon. The ancient Devuni Kadapa temple (considered the gateway to Tirumala), the famous Kadapa stone used in temple construction worldwide, and the Brahmamgari Matham ashram add to Kadapa\'s diverse attractions.', category: 'Historic City', highlights: ['Gandikota Fort', 'Grand Canyon of India', 'Devuni Kadapa Temple', 'Brahmamgari Matham', 'Penna River Gorge', 'Kadapa Stone Quarries'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏛️' },
    { name: 'Nandyal', slug: 'nandyal', desc: 'A picturesque town surrounded by nine sacred Nandi hills — giving the town its name (Nava + Nandi). Famous for the ancient Mahanandi Temple where natural spring water flows directly from the ground beneath the Shiva lingam, creating a unique spiritual experience. The beautiful Belum Caves access point, the ancient Srisailam Temple access (one of the 12 Jyotirlingas), and the lush Rollapadu grasslands make Nandyal a spiritually significant nature destination.', category: 'Temple Town', highlights: ['Mahanandi Temple', 'Nine Nandi Hills', 'Srisailam Access', 'Natural Springs', 'Belum Caves Access', 'Gandikota Access'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🛕' },
    { name: 'Ongole', slug: 'ongole', desc: 'Famous worldwide for the Ongole breed of cattle — massive, sturdy bulls that are prized across India and exported globally for breeding. The beautiful Prakasam Barrage on the Gundlakamma River, the ancient Kashi Vishweswara Swamy Temple, the pristine Vodarevu Beach, and the city\'s strategic location as a major transit hub between Chennai and Vijayawada make Ongole an interesting stop for travelers exploring Andhra Pradesh.', category: 'Coastal Town', highlights: ['Ongole Beach', 'Kashi Vishweswara Temple', 'Vodarevu Beach', 'Ongole Cattle Breed', 'Prakasam Barrage', 'Chengalamma Temple'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🐄' },
    { name: 'Kakinada', slug: 'kakinada', desc: 'Major port city and the second largest city of Andhra Pradesh after Visakhapatnam. Known for the beautiful Uppada Beach with its golden sands, the Coringa Wildlife Sanctuary (home to the endangered fishing cat), the delicious Kakinada Kaja sweet (a flaky, syrup-soaked pastry famous across South India), and its growing IT and industrial sectors. The city also serves as a gateway to the beautiful Godavari delta region and the scenic Konaseema area.', category: 'Port City', highlights: ['Uppada Beach', 'Coringa Sanctuary', 'Kakinada Port', 'Kakinada Kaja Sweet', 'Godavari Delta', 'Coringa Mangroves'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🚢' },
    { name: 'Eluru', slug: 'eluru', desc: 'Historic city known as the Vellalacheruvu of Andhra for its ancient water management systems. Famous for the incredible Eluru Buddha Stupa — a 2nd century BCE Buddhist site with crystal reliquaries, the massive Kolleru Lake (one of the largest freshwater lakes in India and a Ramsar wetland site), the ancient Dwaraka Tirumala Venkateswara Temple, and the beautiful handloom weaving traditions producing the famous Eluru fabrics.', category: 'Heritage Town', highlights: ['Kolleru Lake', 'Eluru Buddha Stupa', 'Dwaraka Tirumala Temple', 'Handloom Weaving', 'Vellalacheruvu', 'Pedavegi Buddhist Site'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🏛️' },
    { name: 'Srikakulam', slug: 'srikakulam', desc: 'Northernmost coastal district of Andhra Pradesh, famous for the ancient Arasavalli Sun Temple — one of the very few Sun temples in India, where the sun\'s rays directly illuminate the idol twice a year during equinoxes. The beautiful Baruva Beach with its ancient Konetiamma temple, the historic Kalingapatnam port (ancient gateway for Buddhist maritime trade), and the unique Srikurmam Temple — the only temple dedicated to Kurma (tortoise) avatar of Lord Vishnu — make Srikakulam culturally rich.', category: 'Coastal Town', highlights: ['Arasavalli Sun Temple', 'Baruva Beach', 'Srikurmam Temple', 'Kalingapatnam Port', 'Telineelapuram Bird Sanctuary', 'Mandasa Fort'], bestTime: 'Oct - Feb', duration: '1-2 Days', emoji: '🏖️' },
    { name: 'Vizianagaram', slug: 'vizianagaram', desc: 'Historic city known for the magnificent Vizianagaram Fort built by the Gajapati Rajas in 1713, featuring stunning defensive architecture, a moat, and beautiful palaces within its walls. The famous annual Pydithalli Ammavari festival drawing hundreds of thousands, the ancient Kumili temples, the prestigious Maharaja\'s College (one of the oldest educational institutions in South India), and the rich Kalinga heritage visible in the architecture and culture make Vizianagaram a heritage destination.', category: 'Heritage City', highlights: ['Vizianagaram Fort', 'Pydithalli Temple', 'Kumili Temple', 'Maharaja College', 'Kalinga Heritage', 'Bobbili Fort'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🏛️' },
    { name: 'Tenali', slug: 'tenali', desc: 'Known as Andhra\';s Paris — birthplace of the legendary Tenali Ramakrishna, the witty poet in Sri Krishna Devaraya\';s court whose stories are beloved across India. A cultural and literary center with beautiful temples like the Ghantasala Buddhist site, the ancient Undavalli Caves with their remarkable rock-cut architecture dating to the 4th-5th century, and the famous Guntur-Prakasam canal network creating lush agricultural landscapes. The city celebrates its literary heritage with passion.', category: 'Cultural Town', highlights: ['Tenali Ramakrishna Legacy', 'Undavalli Caves', 'Cultural Programs', 'Canal Gardens', 'Buddhist Heritage', 'Agricultural Heartland'], bestTime: 'Oct - Feb', duration: '1 Day', emoji: '🎭' },
  ],
};

export const GOA: StateData = {
  name: 'Goa', slug: 'goa', coverImg: '/states/goa-cover.jpg',
  tagline: 'Beach Paradise', tagColor: 'text-pink-400', icon: '🏖️', accentColor: 'pink',
  heroDesc: "Sun-kissed beaches, Portuguese heritage churches, thrilling water sports, and vibrant nightlife — India's favorite holiday destination.",
  places: [
    { name: 'Panaji (Panjim)', slug: 'panaji', desc: 'The charming capital of Goa with the colorful Portuguese-era buildings of the Fontainhas Latin Quarter — the oldest and most picturesque neighborhood in Panaji with pastel-colored houses, art galleries, and cafes. The beautiful Mandovi River cruise, the vibrant Saturday Night Market at Arpora, the iconic Immaculate Conception Church with its stunning baroque staircase, and the bustling Panaji market make this city a delightful blend of Portuguese heritage and Goan charm.', category: 'Capital City', highlights: ['Fontainhas Latin Quarter', 'Mandovi River Cruise', 'Immaculate Conception Church', 'Saturday Night Market', 'Don\'t forget to miss Miramar Beach', 'Casino Quarter'], bestTime: 'Nov - Feb', duration: '2-3 Days', emoji: '🏘️' },
    { name: 'Baga Beach', slug: 'baga-beach', desc: 'One of Goa\'s most famous and lively beaches, known for its exciting water sports including parasailing, jet skiing, banana boat rides, and bumper boats. Beach shacks like Britto\'s and Tito\'s serve delicious seafood and cocktails. The vibrant nightlife with famous clubs like Tito\'s, Mambo\'s, and Cafe Mambo make Baga the party capital of North Goa. The beach is also great for swimming, sunbathing, and enjoying spectacular sunset views over the Arabian Sea.', category: 'Beach', highlights: ['Water Sports', 'Beach Shacks', 'Tito\'s & Mambo\'s', 'Parasailing', 'Nightlife', 'Sunset Views'], bestTime: 'Nov - Feb', duration: '2-3 Days', emoji: '🏖️' },
    { name: 'Calangute Beach', slug: 'calangute-beach', desc: 'The Queen of Beaches — Goa\'s largest and most popular beach stretching over 7 kilometers of golden sand along the Arabian Sea. Packed with water activities including jet skiing, windsurfing, and banana boat rides, beachside restaurants serving authentic Goan fish curry rice, souvenir shops, massage parlors, and a buzzing atmosphere that perfectly defines Goan beach culture. The beach connects seamlessly to neighboring Baga and Candolim, creating a continuous stretch of coastal fun.', category: 'Beach', highlights: ['Beach Activities', 'Water Scooter', 'Shopping', 'Beach Dining', 'Flea Market', 'Paragliding'], bestTime: 'Nov - Feb', duration: '2-3 Days', emoji: '🏖️' },
    { name: 'Anjuna Beach', slug: 'anjuna-beach', desc: 'Famous for the legendary Anjuna Flea Market held every Wednesday — one of India\'s oldest and most iconic flea markets with everything from Tibetan jewelry to Indian spices, electronic music, and bohemian clothing. The stunning red laterite cliffs overlooking the turquoise Arabian Sea create a dramatic landscape. Famous for full moon parties that attract international DJs, the historic Mascarenhas Mansion, and a hippie vibe that has persisted since the 1960s when it was a destination for the global counterculture movement.', category: 'Beach', highlights: ['Wednesday Flea Market', 'Red Cliffs', 'Full Moon Parties', 'Vagator Overlook', 'Hippie Culture', 'UV Bar'], bestTime: 'Nov - Feb', duration: '2 Days', emoji: '🏖️' },
    { name: 'Vagator Beach', slug: 'vagator-beach', desc: 'A dramatically scenic beach with impressive laterite cliffs in warm red and orange hues overlooking the Arabian Sea. The famous Chapora Fort — perched on a hilltop with panoramic views of Vagator Beach, Morjim Beach, and the vast Arabian Sea — was made iconic by the Bollywood movie Dil Chahta Hai. Stunning sunset views from the cliff tops, the relaxed atmosphere compared to its neighbor Anjuna, great cliff-jumping spots, and excellent photography opportunities make Vagator a favorite for those seeking both beauty and tranquility.', category: 'Beach', highlights: ['Chapora Fort', 'Sunset Point', 'Red Cliffs', 'Dil Chahta Hai Location', 'Photography', 'Cliff Jumping'], bestTime: 'Nov - Feb', duration: '1-2 Days', emoji: '🌅' },
    { name: 'Colva Beach', slug: 'colva-beach', desc: 'One of South Goa\'s most beautiful and serene beaches with powdery white sand stretching for kilometers along the Arabian Sea. Lined with swaying coconut palm trees, colorful beachside cafes, beach huts, and a peaceful atmosphere perfect for relaxation away from the party crowds of North Goa. The nearby Benaulim Beach, the historic Church of Our Lady of Mercies, and the relaxed Goan village atmosphere make Colva ideal for families and couples seeking a tranquil beach holiday.', category: 'Beach', highlights: ['White Sand', 'Palm Trees', 'Beach Cafes', 'Peaceful Atmosphere', 'Benaulim Beach', 'Goan Village Life'], bestTime: 'Nov - Feb', duration: '2 Days', emoji: '🏖️' },
    { name: 'Palolem Beach', slug: 'palolem-beach', desc: 'A stunning crescent-shaped paradise beach in South Goa, often called one of the most beautiful beaches in Asia. Famous for unique silent noise parties where dancers wear wireless headphones, dolphin spotting boat trips at sunrise, kayaking through calm waters, colorful beach huts lining the shore, and a bohemian atmosphere. The beach\'s gentle curve creates a natural bay with calm waters perfect for swimming. Nearby Butterfly Beach, accessible only by boat or trek, adds to Palolem\'s magical appeal.', category: 'Beach', highlights: ['Crescent Shape', 'Dolphin Trips', 'Silent Parties', 'Beach Huts', 'Butterfly Beach', 'Kayaking'], bestTime: 'Nov - Feb', duration: '2-3 Days', emoji: '🏖️' },
    { name: 'Basilica of Bom Jesus', slug: 'basilica-of-bom-jesus', desc: 'UNESCO World Heritage Site and one of the oldest churches in India, completed in 1605. Houses the mortal remains of St. Francis Xavier — the patron saint of Goa — in a beautifully ornate silver casket. Every ten years, the saint\'s body is exposed for public veneration, drawing millions of pilgrims from across the world. A masterpiece of Baroque architecture with its ornate facade, gilded altars, and stunning interior, the Basilica represents the pinnacle of Portuguese colonial ecclesiastical architecture in Asia.', category: 'Heritage Church', highlights: ['St. Francis Xavier Tomb', 'Baroque Architecture', 'UNESCO Heritage', 'Art Gallery', 'Silver Casket', 'Religious Ceremonies'], bestTime: 'Year Round', duration: '1 Day', emoji: '⛪' },
    { name: 'Se Cathedral', slug: 'se-cathedral', desc: 'One of the largest churches in Asia, dedicated to Saint Catherine of Alexandria, built by the Portuguese between 1562-1619. Features magnificent Portuguese-Gothic style architecture with a stunning Golden Bell — the largest church bell in Goa, known for its rich melodious tone that can be heard across Old Goa. The Tuscan-style exterior, beautiful rose windows, the miraculous Cross of Miracles on the altar, and the serene atmosphere make the Se Cathedral an architectural and spiritual landmark.', category: 'Heritage Church', highlights: ['Golden Bell', 'Gothic Architecture', 'Cross of Miracles', 'Portuguese Heritage', 'Rose Windows', 'Main Chapel'], bestTime: 'Year Round', duration: '1 Day', emoji: '⛪' },
    { name: 'Fort Aguada', slug: 'fort-aguada', desc: 'A magnificent 17th-century Portuguese fort strategically perched on the Sinquerim cliff overlooking the vast Arabian Sea. Built in 1612 to guard against Dutch and Maratha invasions, the fort features a four-storey Portuguese lighthouse — one of the oldest in Asia — and a freshwater spring (Aguada means water) that supplied passing ships. The stunning panoramic ocean views, the well-preserved ramparts and bastions, and the adjacent Taj Fort Aguada Resort within the fort premises make this Goa\'s most iconic heritage monument.', category: 'Fort', highlights: ['Portuguese Lighthouse', 'Ocean Views', 'Freshwater Spring', 'Historic Walls', 'Sinquerim Beach', 'Taj Resort'], bestTime: 'Year Round', duration: '1 Day', emoji: '🏰' },
    { name: 'Chapora Fort', slug: 'chapora-fort', desc: 'The iconic fort made immortal by the Bollywood blockbuster Dil Chahta Hai (2001), where the famous friendship scene was filmed. Perched on a dramatic hilltop at the mouth of the Chapora River, the fort offers breathtaking 360-degree panoramic views of Vagator Beach, the Arabian Sea, and the lush Goan countryside. Originally built by the Portuguese in 1617 on the site of an earlier Muslim fort, the red laterite stone ruins create a romantic atmosphere especially during sunset, making it one of Goa\'s most photographed locations.', category: 'Fort', highlights: ['Dil Chahta Hai Location', 'Hilltop Views', 'Vagator Beach Panorama', 'Historic Ruins', 'Sunset Point', 'Red Laterite'], bestTime: 'Year Round', duration: '1 Day', emoji: '🏰' },
    { name: 'Dudhsagar Falls', slug: 'dudhsagar-falls', desc: 'One of India\'s tallest and most spectacular waterfalls at 310 meters (1,017 feet), located on the Mandovi River within the Bhagwan Mahavir Wildlife Sanctuary. The name means "Sea of Milk" — during monsoon, the four-tiered cascade appears like a milky white stream flowing down the steep mountain face. Accessible by a thrilling jeep safari through the forest or a scenic trek along the railway tracks that pass right beside the falls. The experience of standing before this thundering cascade surrounded by dense tropical forest is truly awe-inspiring.', category: 'Nature', highlights: ['310m Waterfall', 'Bhagwan Mahavir Sanctuary', 'Trekking', 'Mandovi River', 'Jeep Safari', 'Monsoon Beauty'], bestTime: 'Jun - Sep', duration: '1 Day', emoji: '🌊' },
    { name: 'Bhagwan Mahavir Wildlife Sanctuary', slug: 'bhagwan-mahavir-sanctuary', desc: 'The largest wildlife sanctuary in Goa, spread over 240 square kilometers of dense tropical forest in the Western Ghats. Home to diverse wildlife including leopards, Indian bison (gaur), deer, sloth bears, several species of monkeys, exotic birds, butterflies, and reptiles. The famous Devil\'s Canyon — a dramatic gorge with steep rock walls — is a must-visit within the sanctuary. The ancient 12th-century Tambdi Surla Temple made of black basalt, hidden deep within the forest, adds a spiritual dimension to this wildlife paradise.', category: 'Nature', highlights: ['Tropical Forest', 'Wildlife Safari', 'Devil\'s Canyon', 'Tambdi Surla Temple', 'Bird Watching', 'Nature Trails'], bestTime: 'Nov - Mar', duration: '1 Day', emoji: '🌿' },
    { name: 'Margao', slug: 'margao', desc: 'The cultural and commercial capital of Goa, home to the historic Holy Spirit Church — one of the oldest churches in Salcete taluka with magnificent baroque architecture. Known for colorful Portuguese-era mansions like the Seven Gables House, the bustling municipal market selling fresh spices and local produce, and as the gateway to South Goa\'s pristine beaches. The city\'s vibrant culture, excellent Goan restaurants, and proximity to beautiful beaches like Colva and Benaulim make Margao a great base for exploring South Goa.', category: 'City', highlights: ['Holy Spirit Church', 'Municipal Market', 'Portuguese Mansions', 'South Goa Gateway', 'Largo de Igreja Square', 'Goan Cuisine'], bestTime: 'Year Round', duration: '1 Day', emoji: '🏙️' },
    { name: 'Vasco da Gama', slug: 'vasco-da-gama', desc: 'Goa\'s largest city, named after the legendary Portuguese explorer Vasco da Gama who died in Kochi in 1524 and was initially buried here. Home to the historic Mormugao Port — one of India\'s major natural harbors — and the fascinating Naval Aviation Museum, the only such museum in Asia showcasing India\'s naval aviation history. The beautiful Bogmalo Beach with its clean waters and beachside restaurants, the historic St. Andrews Church, and the city\'s colonial-era railway station add to Vasco\'s unique character.', category: 'Port City', highlights: ['Mormugao Port', 'Bogmalo Beach', 'Naval Aviation Museum', 'St. Andrews Church', 'Hollant Beach', 'Japanese Garden'], bestTime: 'Year Round', duration: '1 Day', emoji: '🚢' },
    { name: 'Old Goa', slug: 'old-goa', desc: 'The former capital of Portuguese India (1510-1843) and a UNESCO World Heritage Site. A living museum of Portuguese colonial architecture spanning several centuries, with magnificent churches, convents, and cathedrals concentrated in a compact walkable area. The stunning Se Cathedral, the Basilica of Bom Jesus, the Church of St. Francis of Assisi, the Archaeological Museum, and the Viceroy\'s Arch all stand as testaments to Goa\'s 450-year Portuguese colonial era. The tree-lined streets and serene atmosphere transport visitors back to a bygone golden era.', category: 'Heritage', highlights: ['UNESCO Heritage Zone', 'Churches & Convents', 'Archaeological Museum', 'Portuguese Quarter', 'Viceroy\'s Arch', 'St. Cajetan Church'], bestTime: 'Year Round', duration: '1 Day', emoji: '🏛️' },
  ],
};

export const ALL_STATES: StateData[] = [KARNATAKA, KERALA, TAMIL_NADU, ANDHRA, GOA];

export function getStateData(stateSlug: string): StateData | undefined {
  return ALL_STATES.find(s => s.slug === stateSlug);
}

export function getPlaceData(stateSlug: string, placeSlug: string): { state: StateData; place: Place } | undefined {
  const state = getStateData(stateSlug);
  if (!state) return undefined;
  const place = state.places.find(p => p.slug === placeSlug);
  if (!place) return undefined;
  return { state, place };
}
